FROM python:3.12.3

COPY pytorch-from-centralized-to-federated/server.py server.py
COPY pytorch-from-centralized-to-federated/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

ENTRYPOINT ["python", "server.py"]