FROM python:3.12.3

# Copy only the requirements file and install dependencies
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt


# Copy the application files
COPY fl/cifar-10-batches-py cifar-10-batches-py
COPY fl/client.py client.py
COPY fl/server.py server.py
COPY fl/cifar.py cifar.py

# Set a default command that can be overridden at runtime
CMD ["python", "server.py"]
